### ISSUE TITLE
System Notifications are broken

### ISSUE THREAD

**Issue by reggie7** [Adobe-Consulting-Services/acs-aem-commons#1839]
* [ ] AEM Version: `6.5`
* [ ] ACS AEM Commons Version: `4.0.0`
* [ ] Reproducible on Latest? yes

### Expected Behavior

**System Notifications** work out of the box.

### Actual Behavior

1. An `Exception` is thrown when opening a new Notification Page.
2. When implemented a workaround for the page display - the notifications break the AEM interface.
3. _Dismissible_ option does not work.

### Steps to Reproduce

Create a new **System Notification** and open the page, the result will be an exception:

![exception](https://user-images.githubusercontent.com/5563546/56203326-48173080-6045-11e9-8f88-f1e99a9cbb18.png)

The problem is `XSSAPI slingXssAPI = slingRequest.adaptTo(XSSAPI.class);` being `null`. One can easily workaround this issue by removing all references to this variable in [system-notifications.jsp](http://localhost:4502/crx/de/index.jsp#/apps/acs-commons/components/utilities/system-notifications/system-notifications.jsp). Then there are other issues as well (note that [system-notifications.jsp](http://localhost:4502/crx/de/index.jsp#/apps/acs-commons/components/utilities/system-notifications/system-notifications.jsp) is just presentation of the config page).

Having the config work, we can add a new Notification, but it breaks the interface:

![notification](https://user-images.githubusercontent.com/5563546/56203735-18b4f380-6046-11e9-9aec-42066e08efda.png)

And dismissed leaves empty menus:

![notification-dismissed](https://user-images.githubusercontent.com/5563546/56203763-279ba600-6046-11e9-8467-b466f02e0bda.png)

Also the **Dismissable** option does not work:

![dismiss](https://user-images.githubusercontent.com/5563546/56203835-4d28af80-6046-11e9-9317-df389e1541ff.png)

**Comment by joerghoh** [comment]
Seems to me, that in case that a message is active, the actual output is written twice, you can see that you have 2 times the `<html>` tag plus all the body.

**Comment by joerghoh** [comment]
This might be a side-effect of #1735. The changed implementation of `AbstractHtmlRequestInjector.doFilter()` uses `BufferedHttpServletResponse`, which in turn delegates all work to `BufferedServletOutput`. And the implicit assumption of this implementation that it will always flush all output to the wrapped response object; the buffered content is never supposed to be written to the reponse!

But this assumption is not true for the `AbstractHtmlRequestInjector` which is supposed to inject custom output at a certain location within the generated output. Thus we have the adjusted output plus the original output, causing the above described behavior.

@kwin As you did the implementation of the `BufferedServletOutput` and also adjusted  the `AbstractHtmlRequestInjector`: do you have any idea how to fix this behavior without building a nearly identical functionality without this implicit assumption?

**Comment by kwin** [comment]
This should already be fixed with https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1853/files

**Comment by joerghoh** [comment]
@kwin Thanks, haven't had that commit on my radar.

**Comment by joerghoh** [comment]
I created PR #1861 to address the issue with the non-working editing page.

**Comment by reggie7** [comment]
@joerghoh - thank you, your [PR](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1861) helps a lot, but indeed there is still a problem with the duplicated output in the rendered `HTML`. But I've tried a local branch where I've merged your work with @kwin's [PR](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1853/files) and the mix does the trick fully!
