### ISSUE TITLE
Redirects are not Displayed Properly on ACS AEM Commons Version: 6.10.0

### ISSUE THREAD

**Issue by seer-neil** [Adobe-Consulting-Services/acs-aem-commons#3497]
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 2024.11.18598.20241113T125352Z-241100 - AEM CaaS
* [ ] ACS AEM Commons Version: 6.10.0
* [ ] Reproducible on Latest? yes

### Expected Behavior
Current Redirects should be displayed on ACS Commons Redirect Manager

### Actual Behavior
Current redirects are not displayed on Redirect Manager console. It was working properly since ACS AEM Commons Version 6.7.0

### Steps to Reproduce
1. On AEM Cloud as a Service instance (preferably the version in the required information), install the latest ACS AEM Commons Version 6.10.0 together with your AEM CaaS code. This should be the same workflow as your normal AEM CaaS deployment. Make sure to include your current redirects.
2. On Tools > ACS AEM Commons > Redirect Manager
3. View the redirects.

### Test Configuration Structure
```
conf/
    + redirect-manager/
       + <domain> [sling:folder]
           + settings [sling:folder]
              + redirects[acs-commons/components/utilities/manage-redirects/redirects]
                  - redirect_item_1 [acs-commons/components/utilities/manage-redirects/redirect-row]
```

*** the legacy redirects were made since ACS AEM Commons version 5.4.0 and has been working since ACS AEM Commons 6.7.0

**Comment by YegorKozlov** [comment]
I can't reproduce it on my local 2024.11.18598.20241113T125352Z-241100 and ACS AEM Commons 6.10.0. 
AEM 6.5.22 + ACS 6.10 also works fine for me. 

Does it work on your local ?

**Comment by seer-neil** [comment]
Hi @YegorKozlov , It’s not working on my local environment at the moment. I did test it on a clean local setup before deploying to the cloud instances, but I’m curious about your setup. Did you have your 'legacy' redirects in place before upgrading to ACS AEM Commons 6.10.0? For me, the redirects have been in place since version 5.4.0 and were working fine all the way through 6.7.0.

Right now, my legacy redirects aren’t showing up at all. Would love to hear what you’ve experienced on your end!

![local-sdk-ss](https://github.com/user-attachments/assets/e62c1101-7978-4407-a9d9-fa8e6675884c)

**Comment by YegorKozlov** [comment]
Are you sure you are running 6.10?

Redirect configs now showing up was a bug (https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/3486) which is fixed in 6.10. I do see it working on my local.

**Comment by seer-neil** [comment]
Yes. I am aware and have been following this issue for quite some time now.

Totally running ACS AEM Common Version 6.10.0
![image](https://github.com/user-attachments/assets/d8e11a6f-b599-4808-8fd2-d1d5e33139b5).

This is interesting. Unless I am missing something here.

**Comment by YegorKozlov** [comment]
Do you see the redirects if you access them via the redirect-manager url directly? e.g.
```
*.adobeaemcloud.com/apps/acs-commons/content/redirect-manager.html/conf/my-site/settings/redirects
```

I'd like to confirm if it is the configurations not showing up, or something else. 

I do have tons of legacy redirects and they are working fine. I deployed 6.10 in AEM CaaS and all seems to be good .

**Comment by seer-neil** [comment]
@YegorKozlov I don't see any redirects when accessed it directly using the link you provided.
It is technically the configurations not showing up but I do seem them on the crx.

**Comment by sravanikancharla455** [comment]
@YegorKozlov , I am encountering the same issue. While the problem mentioned in #3486 has been resolved, the redirects created as subfolders (e.g., /conf/my-site/child-site/settings/redirects) are still not appearing. Only the immediate children of the /conf folder seem to be showing up.

@seer-neil

**Comment by YegorKozlov** [comment]
@sravanikancharla455 Did the `/conf/my-site/child-site/settings/redirects` structure work in the past? It never occured to me users that could create such deep hierarchies,  I designed RM to read configurations as immediate children of `/conf`. 

How deep is your hierarchy?

**Comment by sravanikancharla455** [comment]
Yes @YegorKozlov, the `/conf/my-site/child-site/settings/redirects` structure has worked in the past. It was part of our design to organize redirects in a nested hierarchy. The hierarchy we're dealing with is currently up to four levels deep, with some configurations placed further within child-site structures. Would this be an issue with the current implementation, or is there a way to adjust RM to support this deeper nesting?

**Comment by YegorKozlov** [comment]
@sravanikancharla455 The fix is coming. I have an idea how to supported nested hierarchies.

**Comment by ClemensScherzer** [comment]
I'm also facing this issue and I found this commit that changed the logic how you fetch redirect configs:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/06461ddb4e75cc14203428638582901229cf9920
Before it was a sql query that checked for all nodes of type "acs-commons/components/utilities/manage-redirects/redirects", while the new logic will only iterate over the children directly under /conf.
Is there any update on the fix for this?

**Comment by YegorKozlov** [comment]
released in v6.11
